spring:
  datasource:
    url: jdbc:mysql://localhost:3307/admin?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Santiago
    username: root
    password: sasa
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto:  create

name: spring-boot-backend


server:
  port: 8080
  servlet:
    context-path: /api/${name}/v1/
